win_cond_clean_take = [('toothbrush', 'I', {'label': 'in'}),   
            ('dirty plate', 'I', {'label': 'in'}), 
            ('fantasy book', 'I', {'label': 'in'}),
            ('elegant table runner', 'I', {'label': 'in'}),
            ('business suit', 'I', {'label': 'in'}),
            ('sleeping lamp', 'I', {'label': 'in'}),
            ('toy car', 'I', {'label': 'in'}),
            ('wet towel', 'I', {'label': 'in'}),
            ('dumbbell', 'I', {'label': 'in'}),
            ('swimming fins', 'I', {'label': 'in'}),
            ('raw meat', 'I', {'label': 'in'}),
            ('peace of raw meat', 'I', {'label': 'in'}),
            ('cheese', 'I', {'label': 'in'}), 
            ('milk', 'I', {'label': 'in'}), 
            ('evening dress', 'I', {'label': 'in'}), 
            ('yoga mat', 'I', {'label': 'in'}),
            ('toy sword', 'I', {'label': 'in'}),
            ('jump rope', 'I', {'label': 'in'}), 
            ('toilet paper', 'toilet', {'label': 'in'}), 
            ]

win_cond_clean_place = [('toothbrush', 'bathroom sink', {'label': 'on'}),  
            ('peace of raw meat', 'refrigerator', {'label': 'is'}), 
            ('dirty plate', 'dishwasher', {'label': 'in'}), 
            ('fantasy book', 'bookcase', {'label': 'on'}),
            ('business suit', 'wardrobe', {'label': 'in'}),
            ('sleeping lamp', 'bedside table', {'label': 'on'}),
            ('wet towel', 'towel rack', {'label': 'on'}),
            ('dumbbell', 'dumbbell stand', {'label': 'on'}),
            ('swimming fins', 'pool equipment rack', {'label': 'on'}),
            ('raw meat', 'refrigerator', {'label': 'in'}),
            ('cheese', 'refrigerator', {'label': 'in'}), 
            ('milk', 'refrigerator', {'label': 'in'}), 
            ('evening dress', 'wardrobe', {'label': 'in'}), 
            ('yoga mat', 'sport equipment locker', {'label': 'in'}), 
            ('toy car', 'toy storage cabinet', {'label': 'in'}),
            ('toy sword', 'toy storage cabinet', {'label': 'in'}), 
            ('jump rope', 'sport equipment locker', {'label': 'in'}), 
            ('elegant table runner', 'dining table', {'label': 'on'}), 
            ('toilet paper', 'toilet', {'label': 'on'}), 
            ('TV', 'TV table', {'label': 'on'}), 
            ('reading glasses', 'reading table', {'label': 'on'}), 
            ('salt and papper shakers', 'dining table', {'label': 'on'}), 
            ('decorative pillow', 'sofa', {'label': 'on'}), 
            ('felt tip pens', 'study table', {'label': 'on'}), 
            ('candles', 'dining table', {'label': 'on'}),  
            ('alarm clock', 'bedside table', {'label': 'on'}), 
            ('chlorine', 'table for pool chemicals', {'label': 'on'}), 
            ('swimming goggles', 'pool equipment rack', {'label': 'on'}), 
            ('life ring', 'pool equipment rack', {'label': 'on'}), 
            ('school notebooks', 'study table', {'label': 'on'}),  
            ('deodorant', 'bathroom sink', {'label': 'on'}), 
            ('detective book', 'bookcase', {'label': 'on'}), 
            ('gaming consol', 'game consol cabinet', {'label': 'on'}),  
            ('centerpiece', 'dining table', {'label': 'on'}), ]